In [1]:
%%time
import pandas as pd
import numpy as np
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

CPU times: user 1.19 s, sys: 260 ms, total: 1.45 s
Wall time: 1.36 s


In [ ]:
%%time
train = pd.read_csv("30_sec_train.csv")
test = pd.read_csv("30_sec_test.csv")

In [3]:
print(train.shape)
print(test.shape)

(1260000, 11)
(30210603, 11)


In [8]:
train['Unnamed: 0']

0          14786800
1          14786801
2          14786802
3          14786803
4          14786804
             ...   
1259995    26274496
1259996    26274497
1259997    26274498
1259998    26274499
1259999    26274500
Name: Unnamed: 0, Length: 1260000, dtype: int64

In [7]:
train.columns.tolist()

['Unnamed: 0',
 'target',
 'subject',
 'chest_ACC_x',
 'chest_ACC_y',
 'chest_ACC_z',
 'chest_ECG',
 'chest_EMG',
 'chest_EDA',
 'chest_Temp',
 'chest_Resp']

In [3]:
%%time

# # df=df[df.target!=3]
# train=train[train.target!=4]
# test=test[test.target!=4]

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 6.68 µs


In [4]:
features=train.columns.tolist()
features = features[3:]
features

['chest_ACC_x',
 'chest_ACC_y',
 'chest_ACC_z',
 'chest_ECG',
 'chest_EMG',
 'chest_EDA',
 'chest_Temp',
 'chest_Resp']

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260000 entries, 0 to 1259999
Data columns (total 11 columns):
Unnamed: 0     1260000 non-null int64
target         1260000 non-null int64
subject        1260000 non-null int64
chest_ACC_x    1260000 non-null float64
chest_ACC_y    1260000 non-null float64
chest_ACC_z    1260000 non-null float64
chest_ECG      1260000 non-null float64
chest_EMG      1260000 non-null float64
chest_EDA      1260000 non-null float64
chest_Temp     1260000 non-null float64
chest_Resp     1260000 non-null float64
dtypes: float64(8), int64(3)
memory usage: 105.7 MB


In [9]:
%%time
et = ExtraTreesClassifier(n_estimators=20, n_jobs=10, verbose=2,random_state=0)

CPU times: user 53 µs, sys: 7 µs, total: 60 µs
Wall time: 62.9 µs


In [11]:
et.fit(train[features],train['target'])

[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.


building tree 1 of 20
building tree 2 of 20
building tree 3 of 20building tree 4 of 20
building tree 5 of 20

building tree 6 of 20
building tree 7 of 20
building tree 8 of 20building tree 9 of 20

building tree 10 of 20
building tree 11 of 20
building tree 12 of 20
building tree 13 of 20
building tree 14 of 20
building tree 15 of 20building tree 16 of 20

building tree 17 of 20
building tree 18 of 20
building tree 19 of 20
building tree 20 of 20


[Parallel(n_jobs=10)]: Done  12 out of  20 | elapsed:    1.4s remaining:    0.9s
[Parallel(n_jobs=10)]: Done  20 out of  20 | elapsed:    1.9s finished


ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=10,
                     oob_score=False, random_state=0, verbose=2,
                     warm_start=False)

In [12]:
%%time 
y_pred=et.predict(test[features])

[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  12 out of  20 | elapsed:   13.8s remaining:    9.2s
[Parallel(n_jobs=10)]: Done  20 out of  20 | elapsed:   15.7s finished


CPU times: user 1min 20s, sys: 26.1 s, total: 1min 46s
Wall time: 17.9 s


In [19]:
np.unique(y_pred)

array([1, 2, 3, 4])

In [20]:
print(classification_report(test['target'], y_pred))

              precision    recall  f1-score   support

           1       0.89      0.62      0.73  12012702
           2       0.68      0.82      0.74   6661201
           3       0.63      0.83      0.72   3587501
           4       0.68      0.78      0.73   7949199

    accuracy                           0.73  30210603
   macro avg       0.72      0.76      0.73  30210603
weighted avg       0.76      0.73      0.73  30210603



In [21]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

clf = clf.fit(train[features],train['target'])


y_pred = clf.predict(test[features])

In [22]:
print(classification_report(test['target'], y_pred))

              precision    recall  f1-score   support

           1       0.78      0.56      0.65  12012702
           2       0.53      0.66      0.59   6661201
           3       0.48      0.72      0.58   3587501
           4       0.65      0.64      0.65   7949199

    accuracy                           0.63  30210603
   macro avg       0.61      0.65      0.62  30210603
weighted avg       0.66      0.63      0.63  30210603



In [ ]:
# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier(n_neighbors=5)
# classifier.fit(train[feature],train['target'])
# y_pred = classifier.predict(test[feature])

In [ ]:
# print(classification_report(test['target'], y_pred))

In [3]:
!pip3 install xgboost

    100% |████████████████████████████████| 142.8MB 4.6kB/s eta 0:00:01 1% |▋                               | 2.6MB 42.5MB/s eta 0:00:04    9% |███                             | 13.6MB 26.6MB/s eta 0:00:05    11% |███▊                            | 16.8MB 41.6MB/s eta 0:00:04    31% |██████████                      | 44.9MB 27.5MB/s eta 0:00:04    51% |████████████████▌               | 73.4MB 47.5MB/s eta 0:00:02    63% |████████████████████▍           | 90.8MB 45.1MB/s eta 0:00:02    68% |██████████████████████          | 98.1MB 48.6MB/s eta 0:00:01    85% |███████████████████████████▍    | 122.5MB 49.9MB/s eta 0:00:01
    100% |████████████████████████████████| 20.4MB 34kB/s  eta 0:00:01    66% |█████████████████████▍          | 13.6MB 19.7MB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/29/50/a552a5aff252ae915f522e44642bb49a7b7b31677f9580cfd11bcc869976/scipy-1.3.1-cp36-cp36m-manylinux1_x86_64.whl


In [24]:
%%time
from xgboost import XGBClassifier
import xgboost as xgb
from sklearn.metrics import mean_squared_error
xg_reg = xgb.XGBClassifier(n_estimators = 50)
xg_reg.fit(train[features],train['target'])

y_pred = xg_reg.predict(test[features])

CPU times: user 5min 50s, sys: 3.91 s, total: 5min 54s
Wall time: 5min 54s


In [25]:
print(classification_report(test['target'], y_pred))

              precision    recall  f1-score   support

           1       0.78      0.49      0.60  12012702
           2       0.56      0.62      0.59   6661201
           3       0.36      0.61      0.46   3587501
           4       0.66      0.76      0.70   7949199

    accuracy                           0.60  30210603
   macro avg       0.59      0.62      0.59  30210603
weighted avg       0.65      0.60      0.61  30210603



In [26]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

lg.fit(train[features],train['target'])

y_pred = lg.predict(test[features])

/home/sf/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sf/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [30]:
np.unique(y_pred)

array([1, 2, 3, 4])

In [32]:
print(classification_report(test['target'], y_pred))

              precision    recall  f1-score   support

           1       0.58      0.21      0.30  12012702
           2       0.34      0.43      0.38   6661201
           3       0.18      0.39      0.25   3587501
           4       0.43      0.54      0.48   7949199

    accuracy                           0.37  30210603
   macro avg       0.38      0.39      0.35  30210603
weighted avg       0.44      0.37      0.36  30210603



In [33]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=50)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(train[features],train['target'])

y_pred=clf.predict(test[features])

In [34]:
print(classification_report(test['target'], y_pred))

              precision    recall  f1-score   support

           1       0.86      0.57      0.68  12012702
           2       0.66      0.75      0.70   6661201
           3       0.57      0.82      0.67   3587501
           4       0.64      0.76      0.69   7949199

    accuracy                           0.69  30210603
   macro avg       0.68      0.72      0.69  30210603
weighted avg       0.72      0.69      0.69  30210603



In [35]:
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(train[features],train['target'])

#Predict Output
y_pred= model.predict(test[features])

In [36]:
print(classification_report(test['target'], y_pred))

              precision    recall  f1-score   support

           1       0.58      0.25      0.35  12012702
           2       0.37      0.37      0.37   6661201
           3       0.17      0.51      0.26   3587501
           4       0.43      0.43      0.43   7949199

    accuracy                           0.36  30210603
   macro avg       0.39      0.39      0.35  30210603
weighted avg       0.45      0.36      0.37  30210603



In [37]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=50)
# n_estimators = 100 (default)
# loss function = deviance(default) used in Logistic Regression
clf.fit(train[features],train['target'])


array([1, 1, 1, ..., 4, 4, 4])

In [39]:
y_pred=clf.predict(test[features])

In [40]:
print(classification_report(test['target'], y_pred))

              precision    recall  f1-score   support

           1       0.77      0.52      0.62  12012702
           2       0.66      0.65      0.66   6661201
           3       0.38      0.70      0.50   3587501
           4       0.63      0.71      0.67   7949199

    accuracy                           0.62  30210603
   macro avg       0.61      0.64      0.61  30210603
weighted avg       0.66      0.62      0.62  30210603

